# Script to plot found motifs
# MIT License
# Copyright (c) 2021 Nicole Ludwig

library(lubridate)

Sys.setlocale("LC_ALL", 'english')
found.motifs = Sequence = Timesteps = Load = NULL

aggregation <- c("1 second", "2 min", "10 min", "2 hours")

for (a in aggregation) {

  # load data generated by "20_find_patterns"
  load(paste0("data/", a, "/data_", a, ".RData"))
  load(paste0("data/motifs_", a, ".RData"))
  motif.raw <- found.motifs$Motif.raw

  # plot all instances of one motif --------------------------------------------

  for (m in 1:length(motif.raw)) {

    startpoints <- as.POSIXct(data$Time[found.motifs$Indices[[m]]])

    wd <- weekdays(startpoints, abbreviate = TRUE)
    d <- day(startpoints)
    mth <- month(startpoints)
    h <- hour(startpoints)


    identifier <- paste0(wd," ", d, ".",mth, ".")

    # transform the list of raw motifs to a list with x,y data
    dat <- lapply(motif.raw[[m]],
                  function(x) cbind(x = seq_along(x), y = x))

    # set names for the individual sequences
    list.names <- identifier

    # store the length off the individual sequences
    lns <- sapply(dat, nrow)

    # create a data frame with one y variable (all sequences after each other)
    # and a x variable (time steps)
    # add the name of the sequence as third column
    # by repeating the name according to the length of the sequence
    dat          <- as.data.frame(do.call("rbind", dat))
    names(dat)   <- c("Timesteps", "Load")
    dat$Sequence <- rep(list.names, lns)

    dat <- within(dat,
                  Sequence <- factor(Sequence,
                                     levels = mixedsort(unique(dat$Sequence))))

    p <- ggplot(dat, aes(x = Timesteps, y = Load, colour = Sequence)) +
      theme_bw() +
      geom_line() +
      facet_wrap(~ Sequence) +
      theme(legend.position = "none")

    pdf.plot(p, n = paste0(a, "_eMotif_", m), w = 14, h = 10)

  }
}


print("All Motifs plotted ... ")

rm(list = ls())
